[2019-01-24 08:48:40,512] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.102 - - [24/Jan/2019 08:48:40] "POST /video/computer_lab HTTP/1.1" 200 -
[2019-01-24 08:48:49,576] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.102 - - [24/Jan/2019 08:48:49] "GET /video_feed HTTP/1.1" 200 -
[2019-01-24 08:51:53,144] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.102 - - [24/Jan/2019 08:51:53] "POST /video/computer_lab HTTP/1.1" 200 -
[2019-01-24 08:51:53,203] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.102 - - [24/Jan/2019 08:51:53] "GET /video_feed HTTP/1.1" 200 -
[2019-01-24 08:51:56,994] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} ERROR - Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 242, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe
[2019-01-24 08:52:04,080] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} ERROR - Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 242, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe
[2019-01-24 10:12:51,213] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:12:51] "GET / HTTP/1.1" 200 -
[2019-01-24 10:12:58,902] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:12:58] "POST /video/computer_lab HTTP/1.1" 200 -
[2019-01-24 10:13:10,870] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:13:10] "GET /video_feed HTTP/1.1" 200 -
[2019-01-24 10:13:59,343] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:13:59] "POST /video/computer_lab HTTP/1.1" 200 -
[2019-01-24 10:13:59,355] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:13:59] "GET /video_feed HTTP/1.1" 200 -
[2019-01-24 10:14:03,304] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} ERROR - Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 242, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe
[2019-01-24 10:14:08,754] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} ERROR - Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 242, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe
[2019-01-24 10:14:10,942] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:14:10] "POST /status/computer_lab HTTP/1.1" 200 -
[2019-01-24 10:20:51,485] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:20:51] "GET / HTTP/1.1" 200 -
[2019-01-24 10:20:56,485] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:20:56] "POST /video/computer_lab HTTP/1.1" 200 -
[2019-01-24 10:21:05,894] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:21:05] "GET /video_feed HTTP/1.1" 200 -
[2019-01-24 10:21:16,484] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:21:16] "POST /video/computer_lab HTTP/1.1" 200 -
[2019-01-24 10:21:16,496] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:21:16] "GET /video_feed HTTP/1.1" 200 -
[2019-01-24 10:21:21,103] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} ERROR - Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 242, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe
[2019-01-24 10:21:27,279] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} ERROR - Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 242, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe
[2019-01-24 10:31:37,460] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:31:37] "GET / HTTP/1.1" 200 -
[2019-01-24 10:31:42,595] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:31:42] "POST /video/CEARS HTTP/1.1" 200 -
[2019-01-24 10:31:55,710] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:31:55] "GET /video_feed HTTP/1.1" 200 -
[2019-01-24 10:32:17,728] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:32:17] "POST /video/CEARS HTTP/1.1" 200 -
[2019-01-24 10:32:17,740] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:32:17] "GET /video_feed HTTP/1.1" 200 -
[2019-01-24 10:32:21,843] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} ERROR - Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 242, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe
[2019-01-24 10:32:28,064] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} ERROR - Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 242, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe
[2019-01-24 10:32:28,244] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:32:28] "GET /list_experiments? HTTP/1.1" 200 -
[2019-01-24 10:32:48,533] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:32:48] "GET /check_experiment/1548343937733 HTTP/1.1" 200 -
[2019-01-24 10:37:13,482] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 128.173.79.125 - - [24/Jan/2019 10:37:13] "GET / HTTP/1.1" 200 -
[2019-01-24 11:47:50,101] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2019-01-24 11:47:50,117] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Restarting with stat
[2019-01-24 11:47:50,364] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} WARNING -  * Debugger is active!
[2019-01-24 11:47:50,381] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Debugger PIN: 844-574-987
[2019-01-24 11:48:09,909] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 11:48:09] "GET / HTTP/1.1" 200 -
[2019-01-24 11:48:12,406] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 11:48:12] "POST /status HTTP/1.1" 200 -
[2019-01-24 11:48:16,957] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 11:48:16] "POST /video/computer_lab HTTP/1.1" 200 -
[2019-01-24 11:48:20,152] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 11:48:20] "GET /video_feed HTTP/1.1" 200 -
[2019-01-24 11:48:34,153] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 11:48:34] "POST /video/computer_lab HTTP/1.1" 200 -
[2019-01-24 11:48:34,221] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 11:48:34] "GET /video_feed HTTP/1.1" 200 -
[2019-01-24 11:48:49,274] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
